return {
  "mason-org/mason.nvim",
  cmd = "Mason",
  -- keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
  build = ":MasonUpdate",
  opts_extend = { "ensure_installed" },
  opts = {
    ensure_installed = {
      "delve",
      "gofumpt",
      "goimports",
      "golangci-lint",
      "gomodifytags",
      "gopls",
      "impl",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "prettierd",
      "shfmt",
      "stylua",
      "taplo",
      "yaml-language-server",
    },
  },
}
